version: '2'
services:
  timescale:
    image: timescale/timescaledb:1.6.0-pg10
    container_name: timescale
    ports:
        - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgrespassword
    volumes:
    - db_data:/var/lib/postgresql/data
volumes:
  db_data: